# Generated by Django 5.0.2 on 2024-02-29 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_contacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='yearofbirth',
            new_name='YearOfBirth',
        ),
    ]
